import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Brain, Play, Zap, Activity, ArrowRight } from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="flex items-center justify-between px-4 h-16 border-b">
        <div className="flex items-center space-x-2">
          <Zap className="h-6 w-6" />
          <span className="text-xl font-semibold">LockedIn</span>
        </div>
        <nav className="hidden md:flex items-center space-x-6">
          <Link href="#features" className="text-sm text-muted-foreground hover:text-foreground">
            Features
          </Link>
          <Link href="#pricing" className="text-sm text-muted-foreground hover:text-foreground">
            Pricing
          </Link>
          <Link href="#about" className="text-sm text-muted-foreground hover:text-foreground">
            About
          </Link>
        </nav>
        <Button variant="outline" asChild>
          <Link href="/login">Log In</Link>
        </Button>
      </header>

      <main className="container mx-auto px-4 py-16 space-y-16">
        <section className="text-center space-y-4">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight">
            Transform Your Fitness Journey with LockedIn
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Personalized workouts, expert guidance, and real-time posture monitoring.
            Your AI personal trainer, available 24/7.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
            <Button size="lg" className="font-semibold">
              Get Started
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
            <Button size="lg" variant="outline">
              Learn More
            </Button>
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="p-6 space-y-3">
            <Play className="h-8 w-8 text-primary" />
            <h3 className="text-lg font-semibold">Video Library</h3>
            <p className="text-sm text-muted-foreground">
              Access a vast collection of workout videos for reference and inspiration.
            </p>
          </div>
          <div className="p-6 space-y-3">
            <Brain className="h-8 w-8 text-primary" />
            <h3 className="text-lg font-semibold">AI-Assisted Workouts</h3>
            <p className="text-sm text-muted-foreground">
              Get personalized workout plans generated by our advanced AI.
            </p>
          </div>
          <div className="p-6 space-y-3">
            <Zap className="h-8 w-8 text-primary" />
            <h3 className="text-lg font-semibold">Quick Workouts</h3>
            <p className="text-sm text-muted-foreground">
              Short on time? Choose from our selection of effective quick workouts.
            </p>
          </div>
          <div className="p-6 space-y-3">
            <Activity className="h-8 w-8 text-primary" />
            <h3 className="text-lg font-semibold">Posture Monitoring</h3>
            <p className="text-sm text-muted-foreground">
              Receive real-time feedback on your form to prevent injuries and maximize results.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}